package com.csye6225.fall2018.courseservice.datamodel;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Course")
public class Course {

	private String Id;
	private String courseId;
	private String professId;
	private String taId;
	private String department;
	private String boardId;
	private List<Student> listOfRegisteredStudents;
	private List<Announcements> listOfRegisteredRosters;

	public Course() {
	}

	public Course(String Id, String courseId, String professId, String taId, String department, String boardId,
			List<Student> listOfRegisteredStudents, List<Announcements> listOfRegisteredRosters) {
		this.Id = Id;
		this.courseId = courseId;
		this.professId = professId;
		this.taId = taId;
		this.department = department;
		this.boardId = boardId;
		this.listOfRegisteredStudents = listOfRegisteredStudents;
		this.listOfRegisteredRosters = listOfRegisteredRosters;
	}

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}

	@DynamoDBIndexHashKey(attributeName = "courseId", globalSecondaryIndexName = "courseId-index")
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@DynamoDBAttribute(attributeName = "professId")
	public String getProfessId() {
		return professId;
	}

	public void setProfessId(String professId) {
		this.professId = professId;
	}

	@DynamoDBAttribute(attributeName = "taId")
	public String getTaId() {
		return taId;
	}

	public void setTaId(String taId) {
		this.taId = taId;
	}

	@DynamoDBAttribute(attributeName = "department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}

	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute(attributeName = "listOfRegisteredStudents")
	public List<Student> getListOfRegisteredStudents() {
		return listOfRegisteredStudents;
	}

	public void setListOfRegisteredStudents(List<Student> listOfRegisteredStudents) {
		this.listOfRegisteredStudents = listOfRegisteredStudents;
	}

	@DynamoDBAttribute(attributeName = "listOfRegisteredRosters")
	public List<Announcements> getListOfRegisteredRosters() {
		return listOfRegisteredRosters;
	}

	public void setListOfRegisteredRosters(List<Announcements> listOfRegisteredRosters) {
		this.listOfRegisteredRosters = listOfRegisteredRosters;
	}

}
